export declare const STRING = '[object String]'
export declare const NUMBER = '[object Number]'
export declare const OBJECT = '[object Object]'
export declare const ARRAY = '[object Array]'
export declare const FUNCTION = '[object Function]'
export declare const SYMBOL = '[object Symbol]'
