export declare const isString: (target: any) => boolean
export declare const isNumber: (target: any) => boolean
export declare const isObject: (target: any) => boolean
export declare const isArray: (target: any) => boolean
export declare const isFunction: (target: any) => boolean
export declare const isSymbol: (target: any) => boolean
export declare const isUndefined: (obj: any) => obj is undefined
export declare const isNil: (val: any) => val is null | undefined
export declare const getUserInfo: () => string | null
export declare const getToken: () => string
export declare const getRoleIdList: () => number[]
export declare const setData: (data: Common.StroageType) => void
export declare const removeStorage: (...data: string[]) => boolean
export declare const setLang: (lang: string) => void
export declare const randomKey: () => string
export declare const mapKeys: <T extends Record<string, any>>(obj: T, keyMap: T) => T
export declare const deepClone: <T extends Record<string, any>>(obj: T) => Promise<T>
