# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
# npm ci === npm install

name: feature-demo
 
on: 
  push: 
    branches: 
    - feature/demo 
env:
  DIST_NAME: dist
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Setup Node.js
        uses: actions/setup-node@v3 
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install --force

      - name: Build Package
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.DIST_NAME }}
          path: ${{ env.DIST_NAME }}
      - name: Send Email Notification
        uses: actions/send-email@v1
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: fengkaichao149@163.com
          to: 1491368225@qq.com
          subject: Pipeline Successful
          body: |
            Your pipeline has been successfully executed.
      
